---
title: "Exercise 2"
output: html_notebook
---

## Skovgaard-Olsen et al. (2016): The Relevance Effect and Conditionals

- Conditional = *if-then* statement; e.g., If global warning continues, London will be flooded.
- Bayesian reasoning often assumes 'the Equation': *P*(if *A* then *C*) = *P*(*C*|*A*)
- Our question: Does the Equation hold even if no apparent relationship between *A* and *C*? 
  - positive relevance (PO): *A* is a reason for *C* 
  - negative relevance (NE): *A* is a reason against *C* 
  - irrelevance (IR): *A* and *C* have no apparent relationship 

- 183 (of 348) participants recruited via `crowdflower.com` worked on 12 items.

- Participant first saw a vignette:
  
  > Sophia's scenario: Sophia wishes to find a nice present for her 13-year-old son, Tim, for Christmas. She is running on a tight budget, but she knows that Tim loves participating in live role-playing in the forest and she is really skilled at sewing the orc costumes he needs. Unfortunately, she will not be able to afford the leather parts that such costumes usually have, but she will still be able to make them look nice.

- Then we asked participant for their rating for the conditional probability *P*(*C*|*A*) on the probability scale from 0% to 100%:

  > Suppose Sophia buys a Barbie doll for Tim.   
  > Under this assumption, how probable is it that the following sentence is true:   
  > Tim will be excited about his present.

- On the next page, we asked participant for their rating of the probability of the conditional *P*(if *A* then *C*) on the probability scale from 0% to 100%:

  > Could you please rate the probability that the following sentence is true:   
  > IF Sophia buys a Barbie doll for Tim, THEN Tim will be excited about his present.

### Design

Research question: Does the Equation (i.e., *P*(if *A* then *C*) = *P*(*C*|*A*)) hold even if no apparent relationship between *A* and *C*? 

Full design: 4 x 3 x 2. First two factors repeated-measures, last factor between-subjects.

For each item, participants provide idiosyncratic estimates of *P*(if *A* then *C*) (`dv`) and *P*(*C*|*A*) (`c_given_a`).  
Each participant worked on 12 items, 4 estimates of *P*(*C*|*A*) (`c_given_a`) for each of 3 relevance conditions (`rel_cond`):

- positive relavnce (PO): *A* is a reason for *C* (IF Sophia buys an orc costume for Tim, THEN Tim will be excited about his present.)
- negative relevance (NE): *A* is a reason against *C* (IF Sophia buys a Barbie doll for Tim, THEN Tim will be excited about his present.) 
- irrelevance (IR): *A* and *C* have no apparent relationship (IF Sophia regularly wears shoes, THEN Tim will be excited about his present.)

Type of DV (`dv_question`) is between-subjects condition: 

- Probability of 'if *A* then *C*': How probable is 'if *A* then *C*'?
- Acceptability of 'if *A* then *C*': How acceptable is it to say 'if *A* then *C*'?).
  
Data available at: https://osf.io/j4swp/

## Exercise 2: Analyse the data using a partial-pooling approach.
- Details follow...

```{r}
# go
```

## References 
- Skovgaard-Olsen, N., Singmann, H., & Klauer, K. C. (2016). The relevance effect and conditionals. *Cognition*, 150, 26-36. https://doi.org/10.1016/j.cognition.2015.12.017
- Wickham, H., & Grolemund, G. (2017). *R for Data Science: Import, Tidy, Transform, Visualize, and Model Data.* Sebastopol  CA: O'Reilly.

